### ISSUE TITLE
bug(ebpf) Alibaba Cloud Linux 3 缺失 rpc_task 定义

### ISSUE THREAD

**Issue by Ghostbaby** [cen-ngc5139/nfs-trace#46]
1. 环境信息如下：
- kernel: Linux iZf8z2xntb50opkun9rehtZ 5.10.134-16.3.al8.x86_64 SMP Tue Mar 26 18:54:05 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

2. 错误信息如下：
```
# ./nfs-trace-linux-amd64 -filter-struct=kiocb -filter-func="^(vfs_|nfs_).*" -all-kmods=true
F0912 16:32:42.723265  787117 log.go:128] Failed to load objects: Verifier error: load program: bad CO-RE relocation:
	func#0 @0
	Unrecognized arg#0 type PTR
	0: R1=ctx(id=0,off=0,imm=0) R10=fp0
	; int kb_nfs_read_d(struct pt_regs *regs)
	0: (bf) r8 = r1
	1: R1=ctx(id=0,off=0,imm=0) R8_w=ctx(id=0,off=0,imm=0) R10=fp0
	; u64 current_time = bpf_ktime_get_ns();
	1: (85) call bpf_ktime_get_ns#5
	2: R0_w=inv(id=0) R8_w=ctx(id=0,off=0,imm=0) R10=fp0
	2: (bf) r6 = r0
	3: R0_w=inv(id=1) R6_w=inv(id=1) R8_w=ctx(id=0,off=0,imm=0) R10=fp0
	; task = (struct rpc_task *)PT_REGS_PARM1(regs);
	3: (79) r3 = *(u64 *)(r8 +112)
	4: R0_w=inv(id=1) R3_w=inv(id=0) R6_w=inv(id=1) R8_w=ctx(id=0,off=0,imm=0) R10=fp0
	; instruction poisoned by CO-RE
	4: (85) call unknown#195896080
	invalid func unknown#195896080
	processed 5 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

program kb_nfs_read_d: load program: bad CO-RE relocation: invalid func unknown#195896080 (17 line(s) omitted)
```

**Comment by Ghostbaby** [comment]
尝试使用龙蜥社区提供 [BTF 文件](https://mirrors.openanolis.cn/coolbpf/btf/x86_64/vmlinux-5.10.134-17.2.al8.x86_64)，加载时报如下错误：
```
# ./cmd/nfs-trace -filter-struct=kiocb -filter-func="^(vfs_|nfs_).*" -all-kmods=true -kernel-btf=/root/vmlinux-5.10.134-17.2.al8.x86_64 -add-funcs="nfs_file_direct_read:1,nfs_file_direct_write:1,nf
s_swap_rw:1,nfs_file_read:1,nfs_file_write:1"
F0913 12:05:19.378170   10310 log.go:128] Failed to load BTF spec: can't read symbols: no symbol section
goroutine 1 [running]:
k8s.io/klog/v2/internal/dbg.Stacks(0x0)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/internal/dbg/dbg.go:35 +0xb5
k8s.io/klog/v2.(*loggingT).output(0x44a4800, 0x3, 0x0, 0xc0000df8f0, 0x1, {0x38e98de, 0x6}, 0x80, 0x0)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:944 +0xa55
k8s.io/klog/v2.(*loggingT).printfDepth(0x44a4800, 0x3, 0x0, {0x0, 0x0}, 0x1, {0x30cef95, 0x1b}, {0xc0002b5d80, 0x1, ...})
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:760 +0x3a5
k8s.io/klog/v2.(*loggingT).printf(0x44a4800, 0x3, 0x0, {0x0, 0x0}, {0x30cef95, 0x1b}, {0xc0002b5d80, 0x1, 0x1})
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:737 +0x8e
k8s.io/klog/v2.Fatalf({0x30cef95, 0x1b}, {0xc0002b5d80, 0x1, 0x1})
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:1666 +0x6f
github.com/cen-ngc5139/nfs-trace/internal/log.Fatalf({0x30cef95, 0x1b}, {0xc0002b5d80, 0x1, 0x1})
        /root/nfs-trace/internal/log/log.go:128 +0x31
main.main()
        /root/nfs-trace/cmd/main.go:77 +0x875
```

**Comment by Ghostbaby** [comment]
尝试自定义 `rpc_task` 编译正常，但是启动报如下错误：
```
# ./nfs-trace-linux-amd64 -filter-struct=kiocb -filter-func="^(vfs_|nfs_).*" -all-kmods=true
F0913 09:21:26.657642  791305 log.go:128] Failed to load objects: Verifier error: load program: bad CO-RE relocation:
	func#0 @0
	Unrecognized arg#0 type PTR
	0: R1=ctx(id=0,off=0,imm=0) R10=fp0
	; task = (struct rpc_task *)PT_REGS_PARM1(regs);
	0: (79) r3 = *(u64 *)(r1 +112)
	1: R1=ctx(id=0,off=0,imm=0) R3_w=inv(id=0) R10=fp0
	; instruction poisoned by CO-RE
	1: (85) call unknown#195896080
	invalid func unknown#195896080
	processed 2 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

program rpc_exit_task: load program: bad CO-RE relocation: invalid func unknown#195896080 (9 line(s) omitted)
goroutine 1 [running]:
k8s.io/klog/v2/internal/dbg.Stacks(0x0)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/internal/dbg/dbg.go:35 +0xb5
k8s.io/klog/v2.(*loggingT).output(0x448ac60, 0x3, 0x0, 0xc00038e0e0, 0x1, {0x38ee80f, 0x6}, 0x80, 0x0)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:944 +0xa55
k8s.io/klog/v2.(*loggingT).printfDepth(0x448ac60, 0x3, 0x0, {0x0, 0x0}, 0x1, {0x30d539c, 0x1e}, {0xc002a9eb80, 0x2, ...})
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:760 +0x3a5
k8s.io/klog/v2.(*loggingT).printf(0x448ac60, 0x3, 0x0, {0x0, 0x0}, {0x30d539c, 0x1e}, {0xc002a9eb80, 0x2, 0x2})
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:737 +0x8e
k8s.io/klog/v2.Fatalf({0x30d539c, 0x1e}, {0xc002a9eb80, 0x2, 0x2})
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:1666 +0x6f
github.com/cen-ngc5139/nfs-trace/internal/log.Fatalf({0x30d539c, 0x1e}, {0xc002a9eb80, 0x2, 0x2})
	/root/workload/nfs-trace/internal/log/log.go:128 +0x31
main.main()
	/root/workload/nfs-trace/cmd/main.go:153 +0x16eb
[root@iZf8z2xntb50opkun9rehtZ gb]# ./nfs-trace-linux-amd64 -filter-struct=kiocb -filter-func="^(vfs_|nfs_).*" -all-kmods=true
F0913 09:21:31.095690  791313 log.go:128] Failed to load objects: Verifier error: load program: bad CO-RE relocation:
	func#0 @0
	Unrecognized arg#0 type PTR
	0: R1=ctx(id=0,off=0,imm=0) R10=fp0
	; task = (struct rpc_task *)PT_REGS_PARM1(regs);
	0: (79) r3 = *(u64 *)(r1 +112)
	1: R1=ctx(id=0,off=0,imm=0) R3_w=inv(id=0) R10=fp0
	; instruction poisoned by CO-RE
	1: (85) call unknown#195896080
	invalid func unknown#195896080
	processed 2 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

program rpc_exit_task: load program: bad CO-RE relocation: invalid func unknown#195896080 (9 line(s) omitted)
goroutine 1 [running]:
k8s.io/klog/v2/internal/dbg.Stacks(0x0)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/internal/dbg/dbg.go:35 +0xb5
k8s.io/klog/v2.(*loggingT).output(0x448ac60, 0x3, 0x0, 0xc0002740e0, 0x1, {0x38ee80f, 0x6}, 0x80, 0x0)
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:944 +0xa55
k8s.io/klog/v2.(*loggingT).printfDepth(0x448ac60, 0x3, 0x0, {0x0, 0x0}, 0x1, {0x30d539c, 0x1e}, {0xc0021ccb40, 0x2, ...})
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:760 +0x3a5
k8s.io/klog/v2.(*loggingT).printf(0x448ac60, 0x3, 0x0, {0x0, 0x0}, {0x30d539c, 0x1e}, {0xc0021ccb40, 0x2, 0x2})
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:737 +0x8e
k8s.io/klog/v2.Fatalf({0x30d539c, 0x1e}, {0xc0021ccb40, 0x2, 0x2})
	/root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:1666 +0x6f
github.com/cen-ngc5139/nfs-trace/internal/log.Fatalf({0x30d539c, 0x1e}, {0xc0021ccb40, 0x2, 0x2})
	/root/workload/nfs-trace/internal/log/log.go:128 +0x31
main.main()
	/root/workload/nfs-trace/cmd/main.go:153 +0x16eb
```

**Comment by Ghostbaby** [comment]
使用 ubuntu 22.04 5.15 BTF 文件，获取的信息有问题：
<img width="485" alt="image" src="https://github.com/user-attachments/assets/094c549f-51d1-472f-8593-82f6abd67d3d">
<img width="1784" alt="image" src="https://github.com/user-attachments/assets/5a376c01-a5bc-413c-9059-c848f0790ce3">
1. 写入两次，每次 20 字节，但是统计到的值是每次 29 字节。

**Comment by Ghostbaby** [comment]
**方法四**
使用内核 5.10.134 进行编译，将 nfs 纳入到内核中重新编译生成 BTF 文件
```
# echo "123456" > gb3
[root@iZf8z2xntb50opkun9rehtZ nfs]# curl http://127.0.0.1:8080/metrics|grep nfs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7317    0  7317    0     0  2381k      0 --:--:-- --:--:-- --:--:-- 2381k
# HELP nfs_read_count NFS read count
# TYPE nfs_read_count gauge
nfs_read_count{container="",dev_id="54",file_id="1228942",file_path="",mount_path="",nfs_server="",node_name="iZf8z2xntb50opkun9rehtZ",pod=""} 0
# HELP nfs_read_latencies NFS read latencies
# TYPE nfs_read_latencies gauge
nfs_read_latencies{container="",dev_id="54",file_id="1228942",file_path="",mount_path="",nfs_server="",node_name="iZf8z2xntb50opkun9rehtZ",pod=""} 0
# HELP nfs_read_size NFS read size
# TYPE nfs_read_size gauge
nfs_read_size{container="",dev_id="54",file_id="1228942",file_path="",mount_path="",nfs_server="",node_name="iZf8z2xntb50opkun9rehtZ",pod=""} 0
# HELP nfs_write_count NFS write count
# TYPE nfs_write_count gauge
nfs_write_count{container="",dev_id="54",file_id="1228942",file_path="",mount_path="",nfs_server="",node_name="iZf8z2xntb50opkun9rehtZ",pod=""} 1
# HELP nfs_write_latencies NFS write latencies
# TYPE nfs_write_latencies gauge
nfs_write_latencies{container="",dev_id="54",file_id="1228942",file_path="",mount_path="",nfs_server="",node_name="iZf8z2xntb50opkun9rehtZ",pod=""} 0
# HELP nfs_write_size NFS write size
# TYPE nfs_write_size gauge
nfs_write_size{container="",dev_id="54",file_id="1228942",file_path="",mount_path="",nfs_server="",node_name="iZf8z2xntb50opkun9rehtZ",pod=""} 29
```
进展：

1. 往 gb3 文件中写入 6 字节的数据，但是采集到的写入字节数还是 29 ，不符合预期。

**Comment by Ghostbaby** [comment]
**方法四**
[https://github.com/libbpf/bpftool/issues/163#issuecomment-2354200893](url)
