### ISSUE TITLE
bug(ebpf)  cilium/ebpf 更新 Percpu Array 报错

### ISSUE THREAD

**Issue by Ghostbaby** [cen-ngc5139/nfs-trace#89]
- 代码
```golang
type MemberFieldsOffset struct {
	Ready                          uint8
	TaskFilesOffset                uint32
	SockFlagsOffset                uint32
	TcpSockCopiedSeqOffset         uint32
	TcpSockWriteSeqOffset          uint32
	StructFilesStructFdtOffset     uint32
	StructFilesPrivateDataOffset   uint32
	StructFileFInodeOffset         uint32
	StructInodeIModeOffset         uint32
	StructFileDentryOffset         uint32
	StructDentryNameOffset         uint32
	StructSockFamilyOffset         uint32
	StructSockSaddrOffset          uint32
	StructSockDaddrOffset          uint32
	StructSockIp6saddrOffset       uint32
	StructSockIp6daddrOffset       uint32
	StructSockDportOffset          uint32
	StructSockSportOffset          uint32
	StructSockSkcStateOffset       uint32
	StructSockCommonIpv6onlyOffset uint32
}
...
	if err := m.Update(0, []*metadata.MemberFieldsOffset{&offset}, ebpf.UpdateAny); err != nil {
		return fmt.Errorf("更新偏移量映射失败: %w", err)
	}
...
```

- 报错
```bash
TARGET_GOARCH=amd64,arm64 FILTER_STRUCT=kiocb go generate
Generating for amd64,arm64
Compiled /root/workload/nfs-trace/internal/binary/nfstrace_x86_bpfel.o
Wrote /root/workload/nfs-trace/internal/binary/nfstrace_x86_bpfel.go
Compiled /root/workload/nfs-trace/internal/binary/nfstrace_arm64_bpfel.o
Wrote /root/workload/nfs-trace/internal/binary/nfstrace_arm64_bpfel.go
cd ./cmd;CGO_ENABLED=0 GOOS=linux GOARCH=amd64   go build -gcflags "all=-N -l" -o nfs-trace
./cmd/nfs-trace --filter-struct=kiocb --filter-func="^(vfs_|nfs_).*" --all-kmods=true --enable-nfs-metrics=true --enable-dns=true
2024/10/19 02:20:03 正在附加 nfs 组的 TracePoint 程序...
2024/10/19 02:20:03 正在附加 sunrpc 组的 TracePoint 程序...
2024/10/19 02:20:03 Attaching kprobes (via kprobe)...
7 / 7 [------------------------------------------------------------------------------------] 100.00% ? p/s
2024/10/19 02:20:03 Attached (ignored 0)
F1019 02:20:03.130738    4200 log.go:130] Failed to update offset map: 更新偏移量映射失败: marshal value: *metadata.MemberFieldsOffset doesn't marshal to 80 bytes
goroutine 1 [running]:
k8s.io/klog/v2/internal/dbg.Stacks(0x0)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/internal/dbg/dbg.go:35 +0xb5
k8s.io/klog/v2.(*loggingT).output(0x454bd80, 0x3, 0x0, 0xc0003800e0, 0x1, {0x397db2e, 0x6}, 0x82, 0x0)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:944 +0xa55
k8s.io/klog/v2.(*loggingT).printfDepth(0x454bd80, 0x3, 0x0, {0x0, 0x0}, 0x1, {0x3146621, 0x1f}, {0xc002ea2890, 0x1, ...})
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:760 +0x3a5
k8s.io/klog/v2.(*loggingT).printf(0x454bd80, 0x3, 0x0, {0x0, 0x0}, {0x3146621, 0x1f}, {0xc002ea2890, 0x1, 0x1})
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:737 +0x8e
k8s.io/klog/v2.Fatalf({0x3146621, 0x1f}, {0xc002ea2890, 0x1, 0x1})
        /root/go/pkg/mod/k8s.io/klog/v2@v2.130.1/klog.go:1666 +0x6f
github.com/cen-ngc5139/nfs-trace/internal/log.Fatalf({0x3146621, 0x1f}, {0xc002ea2890, 0x1, 0x1})
        /root/workload/nfs-trace/internal/log/log.go:130 +0x31
github.com/cen-ngc5139/nfs-trace/internal/run.Run({{{0x7fff6b4615b9, 0xe}, {0x7fff6b4615a5, 0x5}}, {{0x0, 0x0}, {0x0, 0x0}}, {0x1, 0x0, ...}, ...})
        /root/workload/nfs-trace/internal/run/run.go:236 +0x2771
main.main.func1(0xc00030ec08, {0xc000750500, 0x0, 0x5})
        /root/workload/nfs-trace/cmd/main.go:23 +0x5b
github.com/spf13/cobra.(*Command).execute(0xc00030ec08, {0xc0000501f0, 0x5, 0x5})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0x1048
github.com/spf13/cobra.(*Command).ExecuteC(0xc00030ec08)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x9d0
github.com/spf13/cobra.(*Command).Execute(0xc00030ec08)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041 +0x32
main.main()
        /root/workload/nfs-trace/cmd/main.go:29 +0x1a5
make: *** [Makefile:22: run] Error 255
```

**Comment by Ghostbaby** [comment]
总结一下使用 Cilium eBPF 库更新 per-CPU array 的正确方法：

1. 定义映射：
   确保在 BPF 程序中正确定义了 per-CPU array：

   ```c
   struct {
       __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
       __type(key, u32);
       __type(value, struct member_fields_offset);
       __uint(max_entries, 1);
   } __members_offset SEC(".maps");
   ```

2. 准备数据：
   在 Go 代码中，将数据包装在切片中：

   ```go
   offsetSlice := []metadata.MemberFieldsOffset{*offset}
   ```

3. 更新映射：
   使用 `Put` 方法更新映射，确保键是 `uint32` 类型：

   ```go
   err = coll.Maps["__members_offset"].Put(uint32(0), offsetSlice)
   if err != nil {
       log.Fatalf("Failed to put members offset: %v", err)
   }
   ```
  同时，确保值为 struct 类型时，字段类型不要时 `uint8`:
  ```diff
  - Ready                          uint8
  + Ready                          uint32
  ```

4. 错误处理：
   始终检查错误并适当处理。

5. 验证更新：
   可以在更新后立即读取值来验证更新是否成功：

   ```go
   var readOffset []metadata.MemberFieldsOffset
   err = coll.Maps["__members_offset"].Lookup(uint32(0), &readOffset)
   if err != nil {
       log.Fatalf("Failed to read members offset: %v", err)
   }
   log.Printf("Read offset: %+v", readOffset[0])
   ```

6. 内存对齐：
   确保 `MemberFieldsOffset` 结构体在 Go 和 C 中的定义完全一致，包括内存对齐。

7. 使用正确的类型：
   确保使用的是 `[]interface{}` 或与映射值类型匹配的切片。

8. 考虑并发：
   如果有多个 goroutine 访问同一个映射，考虑使用同步机制。

9. 清理：
   在程序结束时关闭映射：

   ```go
   defer coll.Close()
   ```

10. 调试：
    如果遇到问题，可以使用 `bpf_printk` 在内核中打印调试信息，并使用 `cat /sys/kernel/debug/tracing/trace_pipe` 查看输出。

通过遵循这些步骤，您应该能够正确地更新 per-CPU array 类型的 eBPF 映射。记住，per-CPU 映射的每个 CPU 都有一个独立的值，所以在读取时可能需要考虑如何处理多个 CPU 的数据。
